name: Bug report
description: Create a bug report
labels:
 - bug
 - unconfirmed
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report!
  - type: markdown
    attributes:
      value: |
        Please note:
        1. Bug reports without a reproduction may be closed immediately.
        2. General usage questions are not bug reports. Please [submit usage questions on Stack Overflow](https://stackoverflow.com/questions/ask) instead.

        Creating a good bug report takes time, please make sure your [reproduction is minimal](https://stackoverflow.com/help/minimal-reproducible-example).
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    attributes:
      label: Mandatory reproduction URL (CodeSandbox or GitHub repository)
      description: |
        Templates: [CodeSandbox (`pages` directory)](https://codesandbox.io/p/sandbox/next-intl-bug-template-pages-krm37f), [CodeSandbox (`app` directory)](https://codesandbox.io/p/sandbox/next-intl-bug-template-forked-yow8ep)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction description
      description: Describe how the issue can be reproduced based on your provided CodeSandbox or GitHub repository.
      value: |
        Steps to reproduce:
        1. Open reproduction
        2. Click on …
        3. See error: … 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
