name: Bug report
description: Create a bug report
labels:
 - bug
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
  - type: markdown
    attributes:
      value: Note that if you leave out sections it's unlikely that your bug will get fixed and the issue will be closed. Thank you for your understanding.
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    attributes:
      label: Reproduction URL (CodeSandbox)
      description: Here's [a template to get you started](https://codesandbox.io/s/next-intl-template-comtb?file=/pages/index.js).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction description
      description: Describe how the issue can be reproduced based on your provided CodeSandbox
      value: |
        Steps to reproduce:
        1. Open reproduction
        2. Click on …
        3. See error: … 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
